### ISSUE TITLE
Failed to parse subjectAlternativeNamesExtension that has explicitly tagged DistinguishedName

### ISSUE THREAD

**Issue by erikgadireddi** [apple/swift-certificates#186] opened 2024-08-13 00:27 UTC
## Context: 
I was trying to use swift-certificates to load one of our x509 certicates in PEM format (originally created via bouncy castle java library). When I found out the subject alternative names extension could not be parsed.
When I was investigating the structure of asn1 tree. I found out that the library expects that the distiniguishedNames have implicit tag, but the asn1 of my certificate structure has explicit tag. (It explicitly is tagged as sequence after the number [4]).

## Error 
Once the Certificate instance was initialized, the subjectAlternativeNamesExtension getter returned error:
"ASN1Error.unexpectedFieldType: ASN1Identifier(tagNumber: 16, tagClass: universal) SwiftASN1/DER.swift:180"`

### Input ASN1 scheme:
ASN1 Scheme: generated from the hex string below  (https://pkitools.net/pages/ca/asn1.html)
<img width="697" alt="Screenshot 2024-08-13 at 1 42 19" src="https://github.com/user-attachments/assets/e3ae5226-095c-4e88-bf3a-b36831282128">

### HexString representing the binary data of the SubjectAlternativeNamesExtension 
3079a47730753117301506035504030c0e4572696b20476164697265646469310f300d060355040b0c0650656f706c6531143012060a0992268993f22c6401191604636f7270311e301c060a0992268993f22c640119160e6e6f72746f6e6c6966656c6f636b31133011060a0992268993f22c6401191603636f6d

## Code to reproduce the issue:
```
import XCTest

import SwiftASN1
import Crypto
import _CryptoExtras
@testable import X509

 func testSubjectAlternativeNamesExtension() throws {
        /// hex string representing the encoded bytes representing the subjectAlternativeNamesExtension
        let hexString = "3079a47730753117301506035504030c0e4572696b20476164697265646469310f300d060355040b0c0650656f706c6531143012060a0992268993f22c6401191604636f7270311e301c060a0992268993f22c640119160e6e6f72746f6e6c6966656c6f636b31133011060a0992268993f22c6401191603636f6d"
        guard let data = hexString.hexData else {
            return
        }
        let uint8Array: [UInt8] = [UInt8](data)
        let arraySlice: ArraySlice<UInt8> = uint8Array[uint8Array.startIndex..<uint8Array.endIndex]

        let extensionOfCertificate = Certificate.Extension.init(oid: [2, 5, 29, 17], critical: false, value: arraySlice)
        let subjectAlternativeNamesExtension: SubjectAlternativeNames? = try .init(extensionOfCertificate)
        // throws error here  "ASN1Error.unexpectedFieldType: ASN1Identifier(tagNumber: 16, tagClass: universal) SwiftASN1/DER.swift:180"
        guard let subjectAlternativeNamesExtension = subjectAlternativeNamesExtension else {
            fatalError("Should not fail")
        }
        print(subjectAlternativeNamesExtension.description)
        // expected value is DirectoryName("0.9.2342.19200300.100.1.25=com,0.9.2342.19200300.100.1.25=nortonlifelock,0.9.2342.19200300.100.1.25=corp,OU=People,CN=Erik Gadireddi"
    }




// Helper extensions
extension Data {

    public var hexString: String {
        map { String(format: "%02hhx", $0) }.joined()
    }
}
extension String {
    public var hexData: Data? {
        var data = Data(capacity: count / 2)
        guard let regex = try? NSRegularExpression(pattern: "[0-9a-f]{1,2}", options: .caseInsensitive) else {
            return nil
        }
        let range = NSRange(startIndex..., in: self)

        regex.enumerateMatches(in: self, range: range) { match, _, _ in
            let byteString = (self as NSString).substring(with: match!.range)
            let num = UInt8(byteString, radix: 16)!
            data.append(num)
        }

        if data.count > 0 {
            return data
        } else {
            return nil
        }
    }
}
```

## Solution:
Replace this code block on this line with the code below
https://github.com/apple/swift-certificates/blob/2f797305c1b5b982acaa6005d8a9f970cc4e97ff/Sources/X509/GeneralName.swift#L61C67-L61C118
```
case Self.directoryNameTag:
            do {
                self = try DER.explicitlyTagged(rootNode, tagNumber: rootNode.identifier.tagNumber, tagClass: rootNode.identifier.tagClass, { node in
                    return  try .directoryName(DistinguishedName(derEncoded: node))
                })
            } catch {
                self = try .directoryName(DistinguishedName(derEncoded: rootNode, withIdentifier: Self.directoryNameTag))
            }
```
It seems to me the library should be able to parse the DistinguishedName, if it is implicitly or explicitly tagged base on the ASN1 notion and the https://www.rfc-editor.org/rfc/rfc5280 .

**Comment by Lukasa** [comment] 2024-08-13 13:31
Thanks for this, I believe this is likely to be a dupe of #177. I've diagnosed that issue, but haven't yet put together a fix. Closing to keep this tracked on #177.

**Closed by Lukasa** 2024-08-13 13:31 UTC
